### ISSUE TITLE
Tasmota_sendMQTTCommand  correction

### ISSUE THREAD

**Issue by fdmarder** [Schnittcher/IPS-Tasmota#1]
Hi,
the discription for Tasmota_sendMQTTCommand is not correct, the first parameter InstanzID is missing, should be:
Tasmota_sendMQTTCommand($InstanzID, $command, $msg);

Exampel to set an output for 500ms (only for a switch):
Tasmota_sendMQTTCommand(37469, "tele/sonoff33/PulseTime1", "5");
Tasmota_sendMQTTCommand(37469, "tele/sonoff33/POWER1", "ON");

Regards fdmarder

**Comment by Schnittcher** [comment]
Thanks, I will edit the doku.
