### ISSUE TITLE
Problem mit 4Ch Sonoff

### ISSUE THREAD

**Issue by sewo777** [Schnittcher/IPS-Tasmota#14]
Hallo Kai,
habe heute meine ersten 4Ch Sonoffs geflasht.
Im IPS wird der Kanal 1 nicht Aktualisiert. Kanal 2-4 funktionieren ohne Prtobleme.
Wenn ich in der Web oberfläche vom Sonoff oder am Sonoff gerät selbst Kanal 1 betätige, passiert im IPS nichts.
Mit IPS kann ich aber diesen Kanal Schalten.
In der Konsole von Tasmota ist alles OK.
`17:16:41 MQT: stat/4_Kanal_Sonoff/RESULT = {"POWER1":"OFF"}
17:16:41 MQT: stat/4_Kanal_Sonoff/POWER1 = OFF`
Könnte das ein Bug sein?

Gruß

PS:
Im IPS Debug kommt aber alles an. Variable bleibt unverändert.

**Comment by Schnittcher** [comment]
Du musst in der Instanz Multi Switch aktivieren.

Grüße,
Kai

**Comment by sewo777** [comment]
Danke für die Info. (Steht sogar in der Doku)
Funktioniert!

Gruß

**Comment by Schnittcher** [comment]
Kein Problem.

Grüße,
Kai
