### ISSUE TITLE
setPower values

### ISSUE THREAD

**Issue by SchmitzA** [Schnittcher/IPS-Tasmota#2]
setPower should send messages "ON" or "OFF" rather than "true" and "false".

So translate::PowerFalse should be replaced by "OFF" and translate::PowerTrue by "ON".

**Comment by Schnittcher** [comment]
Wie sieht die Konfiguration in der Instanz aus?

Edit: Die Translate Funktion wird eh bald entfernt, da mit der neuen Tasmota Firmware dies nicht mehr nötig ist.

**Comment by SchmitzA** [comment]
Device Language: English
Power On: ON
Power Off: OFF
Aber nach meinem Verständnis sollten die Werte die per MQTT gesendet werden, sprachunabhängig sein.

**Comment by Schnittcher** [comment]
Siehe meint "Edit" das ist nur mit den neuen Firmware Versionen so, früher war es anders. Daher gibt es diese Funktion noch.
Führt es bei dir zur Zeit zu Problemen?

**Comment by SchmitzA** [comment]
Ja, es klappt nicht ;), sprich: es wird nicht geschaltet

**Comment by Schnittcher** [comment]
Welche Firmware ist bei deinen Geräten installiert? Wenn ich das jetzt für alle umstelle, kann es zu Problemen bei anderen führen.

**Comment by SchmitzA** [comment]
5.12.0g

**Comment by Schnittcher** [comment]
Sonst bearbeitet die Datei erstmal lokal bei dir. Ich werde meine Geräte mal auf die neue Version updaten und schauen was passiert.

**Comment by SchmitzA** [comment]
Hab' ich schon gemacht; klappt bei mir.

**Comment by Schnittcher** [comment]
Dann werde ich beim nächsten Update mal die Translate Funktion rauswerfen, mit einem Hinweis, dass auf die neue Firmware upgedatet werden muss!

Vielen Dank!

**Comment by SchmitzA** [comment]
Gerne!

**Comment by Schnittcher** [comment]
Neue Version ist online!
