### ISSUE TITLE
Multi Switch im LED Modul

### ISSUE THREAD

**Issue by Swifty72** [Schnittcher/IPS-Tasmota#3]
Hallo Kai,
ist es möglich, die Funktion vom Multi Switch auch im LED Modul einzubauen ?

Gruß
Swifty

**Comment by Schnittcher** [comment]
Werde ich machen, sobald das Modul an die neue Tasmota Firmware angepasst ist. Bzw. sobald jemand die Version aus dem dev Branch mit der neuen Firmware getestet hat. Vielleicht hast du ja Lust?

**Comment by Schnittcher** [comment]
Neue Version ist online!
